title: <p align="center"> Vy Pham </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vy-pham-3457a1219/">LinkedIn</a> |
  <a href="https://github.com/IcedAmericano27/">GitHub</a>
  </p>
  
  <p align="justify">
  Master degree in Business Information System at Monash University.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
